config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  mount Ckeditor::Engine => '/ckeditor'
  resources :posts
  get '/admin', to: 'posts#admin', as: 'admin'
  get '/contact', to: 'contacts#contact', as:'contact'
  get '/entrepreneurship', to: 'posts#entrepreneurship', as:'entrepreneurship'
  get '/startups', to: 'posts#startups', as:'startups'
  get '/learn', to: 'posts#learn', as:'learn'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "posts#index"

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    url: '/ckeditor_assets/attachments/:id/:filename',
                    path: ':rails_root/public/ckeditor_assets/attachments/:id/:filename'

  validates_attachment_presence :data
  validates_attachment_size :data, less_than: 100.megabytes
  do_not_validate_attachment_file_type :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    url: '/ckeditor_assets/pictures/:id/:style_:basename.:extension',
                    path: ':rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension',
                    styles: { content: '800>', thumb: '118x100#' }

  validates_attachment_presence :data
  validates_attachment_size :data, less_than: 2.megabytes
  validates_attachment_content_type :data, content_type: /\Aimage/

  def url_content
    url(:content)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  has_attached_file :avatar, styles: {

    large:"1000x1000>" ,
    medium: "300x300>",
    thumb: "100x100>" }, default_url: "/images/:style/missing.png"

  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  extend FriendlyId
  friendly_id :title, use: :slugged
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def contact
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!, only: [:new, :edit, :create, :update, :destroy, :admin]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
    @most_recent_post = Post.order("created_at DESC").limit(1)
  end

# Entrepreneurship category
  def entrepreneurship
    @posts = Post.where(category: "Entrepreneurship")
  end

# Startups category
  def startups
    @posts = Post.where(category: "Startups")
  end

# Startups category
  def learn
    @posts = Post.where(category: "Start a Business")
  end

# Admin page
  def admin
    @posts = Post.all
    render layout: false
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to :admin, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to :admin, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to :admin, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.fetch(:post).permit(:title, :content, :info, :category, :avatar, :subtitle)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/contacts/contact.html.erb
<div class="d-flex flex-column align-items-center justify-content-center m-4 mb-5">
  <h1 class="mb-4">Contact</h1>
  <p class="mb-5">If you would like to reach out to us, please fill out that form. We'll answer as soon as possible</p>

  <form method="POST" action="https://formspree.io/contact@vnak.co" class="d-flex flex-column" class="mb-4">
    <input type="text" name="name" placeholder="Name" class="mb-4 rounded form-control">
    <input type="email" name="_replyto" placeholder="Email" class="mb-4 rounded form-control" id="ContactEmail">
    <input type="text" name="_gotcha" style="display:none" />
    <textarea name="Message" placeholder="Message" class="mb-4 rounded form-control" id="ContactTextarea" rows="4"></textarea>
    <input type="submit" value="Send" class="btn-success rounded create-post-btn mt-3">
    <input type="hidden" name="_next" value="vnak.co" />
    <input type="hidden" name="_subject" value="New submission!" />
  </form>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Montserrat:100,200,400" rel="stylesheet">
    <%= favicon_link_tag 'VNAK Logo.png' %>
    <%= csrf_meta_tags %>
    <%= javascript_include_tag Ckeditor.cdn_url%>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-99984368-1', 'auto');
        ga('send', 'pageview');
    </script>
    <!-- Google Tag Manager -->
    <script>
      (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
      new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
      j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
      'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
      })(window,document,'script','dataLayer','GTM-NNPTNFB');
    </script>
    <!-- End Google Tag Manager -->
  </head>

  <body>
    <!-- Google Tag Manager (noscript) -->
    <noscript>
        <iframe src="https://www.googletagmanager.com/ns.html?id=GTM-NNPTNFB" height="0" width="0" style="display:none;visibility:hidden"></iframe>
    </noscript>
    <!-- End Google Tag Manager (noscript) -->
    <nav class="navbar navbar-toggleable-md navbar-inverse sticky-top">
      <div class="d-flex flex-row justify-content-around">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <span class="navbar-text ml-5">
          <%= link_to "VNAK", posts_path, class:"text-white"%>
        </span>
      </div>
        <div class="collapse navbar-collapse justify-content-end" id="navbarTogglerDemo01">
          <ul class="navbar-nav mt-2 mt-lg-0">
            <li class="nav-item">
              <%=link_to "Entrepreneurship", entrepreneurship_path, class:"nav-link"%>
            </li>
            <li class="nav-item">
              <%=link_to "Startups", startups_path, class:"nav-link"%>
            </li>
            <li class="nav-item">
              <%=link_to "Become an Entrepeneur", learn_path, class:"nav-link"%>
            </li>
            <form class="d-flex flex-row ml-5 mr-5" style="height: 2.1rem;" method="POST" action="https://formspree.io/contact@vnak.co">
              <input class="form-control mr-2" style="width: 12rem;" type="email" placeholder="Email" name="Email">
              <button class="btn btn-outline-success align-self-center" type="submit">Follow</button>
              <input type="hidden" name="_next" value="vnak.co" />
            </form>
          </ul>
        </div>
    </nav>
    <%= yield %>

    <footer class="d-flex flex-row rounded-top">
      <div class="categories-footer col-4 mt-3">
        <h6 class="footer-title">Categories</h6>
        <ul class="footer-list list-unstyled">
          <li><%=link_to "Entrepreneurship", entrepreneurship_path, class:"footer-link"%></li>
          <li><%=link_to "Startups", startups_path, class:"footer-link"%></li>
          <li><%=link_to "Become an Entrepeneur", learn_path, class:"footer-link"%></li>
        </ul>
      </div>
      <div class="contact-footer col-4 mt-3">
        <h6 class="footer-title">About</h6>
        <ul class="footer-list list-unstyled">
          <li><a class="footer-link" href="#">Authors</a></li>
          <li><%=link_to "Partnerships", contact_path, class:"footer-link"%></li>
          <li><a class="footer-link" href="#">Terms</a></li>
          <li><%=link_to "Contact", contact_path, class:"footer-link"%></li>
        </ul>
      </div>
        <div class="social-media-footer col-4 mt-3">
          <h6 class="footer-title">Follow us</h6>
          <ul class="footer-list list-unstyled">
            <li><a class="footer-link" href="https://www.facebook.com/VNAK-1213349072121802/">Facebook</a></li>
            <li><a class="footer-link" href="https://twitter.com/VNAK_blog">Twitter</a></li>
            <li><a class="footer-link" href="https://www.linkedin.com/company-beta/18117507">LinkedIn</a></li>
          </ul>
      </div>
    </footer>
  </body>
</html>

app/views/posts/_form.html.erb
<%= simple_form_for(@post, multipart: true) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:" %>
      </h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
          <% end %>
      </ul>
    </div>
  <% end %>

  <div class="d-flex justify-content-center mb-3">
    <%= f.label :image, class:"mr-4" %>
    <%= f.file_field :avatar %>
  </div>

  <div class="d-flex justify-content-end mb-3 mr-5 form-input">
    <%= f.input :title %>
  </div>

  <div class="d-flex justify-content-end mb-3 mr-5 form-input">
    <%= f.input :subtitle, class: "form-control" %>
  </div>

  <div class="d-flex justify-content-center mb-3">
    <%= f.input :content, as: :ckeditor, input_html: {ckeditor: {toolbar: 'FULL'}} %>
  </div>

  <div class="d-flex justify-content-center mb-3">
    <%=f.label :Category, class:"mr-4 mt-2" %>
    <%=f.select :category, options_for_select(["Entrepreneurship", "Startups", "Start a Business"])%>
  </div>

  <div class="d-flex justify-content-center m-5">
    <%= f.button :submit, class:"btn-success rounded create-post-btn" %>
  </div>
<% end %>

app/views/posts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Montserrat:100,200,400" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= javascript_include_tag Ckeditor.cdn_url%>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <nav class="navbar navbar-toggleable-md navbar-inverse sticky-top">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
        <% if admin_signed_in? %>
          <span><strong class="navbar-text text-white ml-3"><%= current_admin.email %></strong></span>
            <div class="collapse navbar-collapse justify-content-end mr-3" id="navbarTogglerDemo02">
              <ul class="navbar-nav mt-2 mt-md-0">
                <li class="active">
                  <%= link_to "Home", posts_path, class:"navbar-link btn btn-default navbar-btn"%>
                </li>
                <li class="">
                  <%= link_to 'Edit profile', edit_admin_registration_path, :class => 'navbar-link btn btn-default navbar-btn' %>
                </li>
                <li class="">
                  <%= link_to "Logout", destroy_admin_session_path, method: :delete, :class => 'navbar-link btn btn-default navbar-btn'  %>
                </li>
              </ul>
            </div>
          <% end %>
    </nav>
    <% if notice || alert %>
      <p class="notice d-flex m-3 justify-content-center"><%= notice %></p>
      <p class="alert d-flex m-3 justify-content-center"><%= alert%></p>
    <% end %>

    <div class="d-flex justify-content-end mr-5 mt-3">
      <%= link_to "View as user", posts_path, target: "_blank" %>
    </div>

    <div class="container d-flex flex-column justify-content-center m-5">
    <table class="table table-hover">
      <tbody>
        <tr>
          <td class="text-center">
            <h1>All Posts</h1>
          </td>
          <td class="mt-3 text-center">
            <h1><%= link_to 'New Post', new_post_path %></h1>
          </td>
        </tr>
        <% @posts.each do |post| %>
          <tr>
            <td class="text-center"><%= post.title %></td>
            <td class="text-center d-flex flex-row align-items-center justify-content-center">
              <%= link_to 'Show', post, :target => "_blank", class:"btn btn-success text-white"%>
              <%= link_to 'Edit', edit_post_path(post), class:"btn btn-primary mr-2 ml-2 text-white" %>
              <%= button_to 'Delete',  { action: :destroy, id: post.id }, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    </div>
  </body>
  </html>

app/views/posts/edit.html.erb
<div class="d-flex flex-column align-items-center justify-content-center m-5">

  <h1 class="mb-5">Editing Post</h1>

  <%= render 'form', post: @post %>

  <%= link_to 'Back', admin_path, class:"back-link" %>
</div>

app/views/posts/entrepreneurship.html.erb
<head>
  <title>VNAK | Entrepreneurship</title>
  <meta name="description" content="All our articles about entrepreneurship to help you learn and grow your business">
</head>

<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="mb-4 entrepreneurship-title text-center">Entrepreneurship</h1>
    <p class="lead text-center">All our articles about entrepreneurship to help you learn and grow your business</p>
  </div>
</div>

<div class="d-flex flex-row justify-content-center flex-wrap">
    <% @posts.each do |post| %>
      <div class="card m-4" style="width: 18rem;">
        <%if post.avatar_file_name != nil %>
        <img class="card-img-top" style="height: 200px;" src="<%=post.avatar(:medium)%>" alt="<%=post.avatar_file_name%>">
        <%end%>
        <div class="card-block">
          <h4 class="card-title"><%=post.title%></h4>
          <p class="post-content-index"><%= post.subtitle%></p>
          <%=link_to "Read more", post, class:"read-more-link"%>
        </div>
      </div>
      <br>
    <% end %>
</div>

app/views/posts/index.html.erb
<head>
  <title>VNAK</title>
  <meta name="description" content="Let's get you started with your business. Blog for new entrepreneurs where we share everything entrepreneurship.">
</head>

<% @most_recent_post.each do |most_recent_post|%>
  <div class="jumbotron jumbotron-index rounded-0 d-flex flex-column justify-content-center align-items-center" style="background-image: url('<%=most_recent_post.avatar.url%>')">
      <h1 class="display-4 text-white mt-4">
        <%= most_recent_post.title %>
      </h1>
      <p class="lead mt-5">
        <%=link_to "Read more", most_recent_post, class: "display-5 text-white"%>
      </p>
  </div>
<%end%>

<h1 class="d-flex justify-content-center">Latest Articles</h1>

<div class="d-flex flex-row justify-content-center flex-wrap">
    <% @posts.each do |post| %>
      <div class="card m-4" style="width: 18rem;">
        <%if post.avatar_file_name != nil %>
        <img class="card-img-top" style="height: 200px;" src="<%=post.avatar(:medium)%>" alt="<%=post.avatar_file_name%>">
        <%end%>
        <div class="card-block">
          <h4 class="card-title"><%=post.title%></h4>
          <p class="post-content-index"><%= post.subtitle%></p>
          <%=link_to "Read more", post, class:"read-more-link"%>
        </div>
      </div>
      <br>
    <% end %>
</div>

app/views/posts/learn.html.erb
<head>
  <title>VNAK | Learn</title>
  <meta name="description" content="Get started with your project and become a successful entrepreneur">
</head>

<div class="jumbotron jumbotron-fluid mb-0" style="height: 71vh;">
  <div class="container">
    <h1 class="mb-4 text-center" style="font-size: 2.8rem; font-weight:300;">Become an Entrepeneur</h1>
    <p class="lead text-center">Step by Step guide to starting a business and become successful</p>
    <form class="form-inline justify-content-center mt-5 mb-5" method="POST" action="https://formspree.io/contact@vnak.co">
      <input type="email" class="form-control col-4 mr-2" id="inlineFormInput" placeholder="Email">
      <button type="submit" class="btn btn-success">Get Started</button>
      <input type="hidden" name="_next" value="vnak.co" />
      <input type="hidden" name="_subject" value="Become an Entrepreneur!"/>
    </form>
  </div>
</div>

app/views/posts/new.html.erb
<div class="d-flex flex-column align-items-center justify-content-center m-5">
  <h1 class="mb-5">New Post</h1>

  <%= render 'form', post: @post %>

  <%= link_to 'Back', admin_path, class:"back-link" %>
</div>

app/views/posts/show.html.erb
<head>
  <title><%=@post.title%></title>
  <meta name="description" content="<%=@post.subtitle%>">
  <meta property="fb:app_id" content="115489915741819" />
</head>

<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.9";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<p id="notice"><%= notice %></p>

<div class="d-flex flex-column justify-content-center align-items-center m-5 text-justify">
  <h1><%=@post.title %></h1>
  <p class="mt-3"><%=@post.created_at.strftime("Published on %m/%d/%Y") %></p>
</div>

<div class="d-flex justify-content-center mb-5">
  <% if @post.avatar_file_name != nil%>
    <%= image_tag @post.avatar.url(:large), {style: "width: 75%; height:20%;"}%>
  <%end%>
</div>

<!-- Share buttons BEGIN -->
<div class="a2a_kit a2a_kit_size_32 a2a_default_style" id="share-ul">
  <ul class="nav d-flex flex-column ml-3">
    <li class="nav-item m-2"><a class="a2a_dd" href="https://www.addtoany.com/share"></a></li>
    <li class="nav-item m-2"><a class="a2a_button_facebook"></a></li>
    <li class="nav-item m-2"><a class="a2a_button_twitter"></a></li>
    <li class="nav-item m-2"><a class="a2a_button_kindle_it"></a></li>
  </ul>
</div>
<script async src="https://static.addtoany.com/menu/page.js"></script>
<!-- Share Buttons END -->

  <div class="post-content d-flex flex-column col-9">
    <%= raw @post.content %>
  </div>

  <div class="d-flex justify-content-center mb-5">
    <%= link_to 'Back', posts_path, class:"back-link" %>
  </div>

  <div class="fb-comments d-flex col-9 mb-5" data-width="100%" data-href="http://www.vnak.co/posts" data-numposts="5"></div>


<script>
var span = document.getElementById("share-ul");
span.style.display = "none";

document.addEventListener("scroll", function() {
    if (document.body.scrollTop > 600) {
        span.style.display = "block";
    }
    else {
        span.style.display = "none";
    }
});
</script>

app/views/posts/startups.html.erb
<head>
  <title>VNAK | Startups</title>
  <meta name="description" content="Come and meet new startupers who started their project">
</head>

<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="mb-4 text-center" style="font-size: 3.5rem; font-weight:300;">Startups</h1>
    <p class="lead text-center">Come and meet new startupers who started their project</p>
  </div>
</div>

<div class="d-flex flex-row justify-content-center flex-wrap">
    <% @posts.each do |post| %>
      <div class="card m-4" style="width: 18rem;">
        <%if post.avatar_file_name != nil %>
        <img class="card-img-top" style="height: 200px;" src="<%=post.avatar(:medium)%>" alt="<%=post.avatar_file_name%>">
        <%end%>
        <div class="card-block">
          <h4 class="card-title"><%=post.title%></h4>
          <p class="post-content-index"><%= post.subtitle%></p>
          <%=link_to "Read more", post, class:"read-more-link"%>
        </div>
      </div>
      <br>
    <% end %>
</div>